apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: wordpress-monitoring
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: nginx
  endpoints:
  - port: http
    path: /nginx_status
    interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: wordpress-pods
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: wordpress
  endpoints:
  - port: http
    interval: 30s
