apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress.fullname" . }}-wordpress
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
    app.kubernetes.io/component: wordpress
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wordpress.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: wordpress
  template:
    metadata:
      labels:
        {{- include "wordpress.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: wordpress
    spec:
      containers:
      - name: wordpress
        image: "{{ .Values.image.wordpress.repository }}:{{ .Values.image.wordpress.tag }}"
        imagePullPolicy: {{ .Values.image.wordpress.pullPolicy }}
        env:
        - name: WORDPRESS_DB_HOST
          value: {{ include "wordpress.fullname" . }}-mysql
        - name: WORDPRESS_DB_NAME
          value: {{ .Values.mysql.database | quote }}
        - name: WORDPRESS_DB_USER
          value: {{ .Values.mysql.user | quote }}
        - name: WORDPRESS_DB_PASSWORD
          value: {{ .Values.mysql.password | quote }}
        ports:
        - containerPort: 80
        resources:
          {{- toYaml .Values.resources.wordpress | nindent 10 }}
